import Head from 'next/head'
import { Covered_By_Your_Grace, Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { useState } from 'react';
import ReactSimplyCarousel from 'react-simply-carousel';
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1 className={styles.home}> Welcome </h1>
        <Image 
        src="https://picsum.photos/id/12/1920/1080" 
        alt="Image"
        width={800}
        height={400}
        priority={true}
         />
      </main>
      <body className={styles.body}>

      <h2> Test Gallery</h2>
        
    <ReactSimplyCarouselExample />
      </body>
    </>
  )
}


export function ReactSimplyCarouselExample () {
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);

  return (
    <div>
      <ReactSimplyCarousel
        activeSlideIndex={activeSlideIndex}
        onRequestChange={setActiveSlideIndex}
        itemsToShow={1}
        itemsToScroll={1}
        forwardBtnProps={{
         
          style: {
            alignSelf: 'center',
            background: 'black',
            border: 'none',
            borderRadius: '50%',
            color: 'white',
            cursor: 'pointer',
            fontSize: '20px',
            height: 30,
            lineHeight: 1,
            textAlign: 'center',
            width: 30,
          },
          children: <span>{`>`}</span>,
        }}
        backwardBtnProps={{
          
          style: {
            alignSelf: 'center',
            background: 'black',
            border: 'none',
            borderRadius: '50%',
            color: 'white',
            cursor: 'pointer',
            fontSize: '20px',
            height: 30,
            lineHeight: 1,
            textAlign: 'center',
            width: 30,
          },
          children: <span>{`<`}</span>,
        }}
        
        responsiveProps={[
          {
            itemsToShow: 1,
            itemsToScroll: 1,
            minWidth: 400, 
            maxWidth: 992
          },
        ]}
        speed={500}
        easing="linear"
      >
    
        <div style={{ maxWidth: 600, height: 400, background: '#ff80ed' }}>
          <Image src="https://picsum.photos/id/1/800/400" alt="Image" width={800} height={400} />
        </div>
        <div style={{ maxWidth: 600, height: 400, background: '#065535' }}>
        <Image src="https://picsum.photos/id/2/800/400" alt="Image" width={800} height={400}/>
        </div>
        <div style={{ maxWidth: 600, height: 400, background: '#000000' }}>
        <Image src="https://picsum.photos/id/3/800/400" alt="Image" width={800} height={400}/>
        </div>
        <div style={{ maxWidth: 600, height: 400, background: '#133337' }}>
        <Image src="https://picsum.photos/id/4/800/400" alt="Image" width={800} height={400} />
        </div>
        <div style={{ width: 600, height: 400, background: '#ffc0cb' }}>
        <Image src="https://picsum.photos/id/5/800/400" alt="Image" width={800} height={400}/>
        </div>
      </ReactSimplyCarousel>
    </div>
  );
};